Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,18 +34,18 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          if [ -f "/home/runner/work/starter-workflows/starter-workflows/yarn.lock" ]; then
+  echo "manager=yarn" >> $GITHUB_OUTPUT
+  echo "command=install" >> $GITHUB_OUTPUT
+  exit 0
+elif [ -f "/home/runner/work/starter-workflows/starter-workflows/package.json" ]; then
+  echo "manager=npm" >> $GITHUB_OUTPUT
+  echo "command=ci" >> $GITHUB_OUTPUT
+  exit 0
+else
+  echo "Unable to determine package manager"
+  exit 1
+fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
